# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed58acd3cffbb7472de0b0283b98a484f0465251d351beef904a03fa599991cd0fea06b5a5db7fe68753c7d4e18198c28a21601d9e93d559929380385638fd32

test:
  secret_key_base: 93260e3b218f08a70e31493433dc185637a6b61848c4da67c7d844a616dfd04fcab6cba27cf4cac3c205459de6947d050cd1b09c4a126734a7c88dbd1d4dc591

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
